version: "2"         # required to adjust maintainability checks
checks:
  complex-logic:
    config:
      threshold: 10
  file-lines:
    config:
      threshold: 250
  method-complexity:
    config:
      threshold: 12
  method-lines:
    config:
      threshold: 60
exclude_patterns:
  - "__tests__"  